
public final class Constants {

	static final int MINUTES_OF_HOUR = 60;
	static final int SECONDS_OF_HOUR = 3600;
	
	static final Integer HOURS_SLA_ACKNOWLEDGE_LOW = 16;
	static final Integer HOURS_SLA_ACKNOWLEDGE_MED = 8;
	static final Integer HOURS_SLA_ACKNOWLEDGE_HI = 4;
	static final Integer HOURS_SLA_ACKNOWLEDGE_CRIT = 1;
	
	static final Integer HOURS_SLA_RESOLUTION_LOW = 40;
	static final Integer HOURS_SLA_RESOLUTION_MED = 24;
	static final Integer HOURS_SLA_RESOLUTION_HI = 8;
	static final Integer HOURS_SLA_RESOLUTION_CRIT = 4;
	
	static final Integer MINUTES_SLA_ACKNOWLEDGE_LOW = HOURS_SLA_ACKNOWLEDGE_LOW * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_ACKNOWLEDGE_MED = HOURS_SLA_ACKNOWLEDGE_MED * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_ACKNOWLEDGE_HI = HOURS_SLA_ACKNOWLEDGE_HI * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_ACKNOWLEDGE_CRIT = HOURS_SLA_ACKNOWLEDGE_CRIT * MINUTES_OF_HOUR;
	
	static final Integer MINUTES_SLA_RESOLUTION_LOW = HOURS_SLA_RESOLUTION_LOW * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_RESOLUTION_MED = HOURS_SLA_RESOLUTION_MED * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_RESOLUTION_HI = HOURS_SLA_RESOLUTION_HI * MINUTES_OF_HOUR;
	static final Integer MINUTES_SLA_RESOLUTION_CRIT = HOURS_SLA_RESOLUTION_CRIT * MINUTES_OF_HOUR;
	
	static final Integer SECONDS_SLA_ACKNOWLEDGE_LOW = HOURS_SLA_ACKNOWLEDGE_LOW * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_ACKNOWLEDGE_MED = HOURS_SLA_ACKNOWLEDGE_MED * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_ACKNOWLEDGE_HI = HOURS_SLA_ACKNOWLEDGE_HI * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_ACKNOWLEDGE_CRIT = HOURS_SLA_ACKNOWLEDGE_CRIT * SECONDS_OF_HOUR;
	
	static final Integer SECONDS_SLA_RESOLUTION_LOW = HOURS_SLA_RESOLUTION_LOW * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_RESOLUTION_MED = HOURS_SLA_RESOLUTION_MED * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_RESOLUTION_HI = HOURS_SLA_RESOLUTION_HI * SECONDS_OF_HOUR;
	static final Integer SECONDS_SLA_RESOLUTION_CRIT = HOURS_SLA_RESOLUTION_CRIT * SECONDS_OF_HOUR;
	
	
	
}
